### ISSUE TITLE
Add optional tasks for monolithic install

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-awx#2]
...mainly because I want to understand the architecture a little better, but also because I already have like 90% of the dependencies taken care of with:

```yaml
- src: geerlingguy.repo-epel
- src: geerlingguy.git
- src: geerlingguy.ansible
- src: geerlingguy.pip
- src: geerlingguy.nodejs
- src: geerlingguy.postgresql
- src: geerlingguy.memcached
- src: geerlingguy.rabbitmq
# I want to be able to use this role to do a monolith install.
# - src: geerlingguy.awx
```

It also seems like this kind of installation might be easier to maintain/reason with for very basic single-server installations (e.g. for a small side project or small business that just wants to run the bare minimum on something like a 1GB DigitalOcean droplet—e.g. for Server Check.in :D)
