### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by nandanlbhat** [geerlingguy/ansible-role-awx#24]
I have tried on a fresh VM with CentOS 1804 (RHEL 7.5).

Installed ansible (2.4 from repo).

Installed suggested dependency roles with ansible-galaxy

Install fails complaining "unable to load docker-compose"
[awx.txt](https://github.com/geerlingguy/ansible-role-awx/files/3041635/awx.txt)

**Comment by divansantana** [comment]
Same here. :thinking:

**Comment by divansantana** [comment]
@nandanlbhat did you make any progress with this?

**Comment by nandanlbhat** [comment]
I was able to have awx functional following the guide at https://github.com/ansible/awx/blob/devel/INSTALL.md . So, there is nothing wrong with the main repo. However, looks like there is some problem with this awx role trying to do something with docker-compose. Not much of a dev to troubleshoot.

**Comment by mrpull** [comment]
I believe I ran into something similar this evening on CentOS 7.6.1810.

I changed `awx_run_install_playbook` variable to `no` and later ran the AWX install playbook by hand.  

The installer playbook complained about docker-compose python dependency and later about docker and docker-py being installed.  I resolved those by hand and then tweaked the recommended playbook to the following:

```
---
- name: Install AWX
  hosts: default
  become: true

  vars:
    nodejs_version: "6.x"
    pip_install_packages:
      - name: docker-compose
      - name: docker
    awx_run_install_playbook: yes

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - name: geerlingguy.repo-epel
      when: ansible_os_family == "RedHat"
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.nodejs
    - geerlingguy.awx
```

I destroyed the vagrant host and rebuilt with success.
