### ISSUE TITLE
Inability to use SSL

### ISSUE THREAD

**Issue by insanity54** [geerlingguy/ansible-role-awx#25]
SSL is not able to be configured by a playbook including this role due to the [awx installation playbook being called using ansible command module](https://github.com/ben-le/ansible-role-awx/blob/master/tasks/main.yml#L28).

For example, the following playbook will not configure SSL because the variables relevant to SSL are not passed on to the playbook that is installing awx.

```yaml
- name: Provision Server as AWX server
  hosts: ddi-awx
  roles:
    - role: geerlingguy.git
    - role: geerlingguy.pip
    - role: geerlingguy.ansible
    - role: geerlingguy.docker
    - role: geerlingguy.awx
      ssl_certificate: /tmp/my-ssl.cert
      dockerhub_base: # intentionally left blank to force docker images to be built locally.
```
