### ISSUE TITLE
Broken for AWX 17.0.0 

### ISSUE THREAD

**Issue by mvcaaa** [geerlingguy/ansible-role-awx#39]
There is no default value for `admin_password` anymore

issue-related change in AWX:

https://github.com/ansible/awx/commit/aabb55810b6e93cc22d80dff1dc90d699169ac2e

**Comment by dbauer23** [comment]
Hi, 
on my local copy I added the following task on the beginning in awx-install-playbook.yml to fix that issue.

```
- name: inject custom vars into awx install
  ansible.builtin.lineinfile:
    path: "{{ awx_repo_dir }}/installer/inventory"
    regexp: "^(#\\s?)?{{item.key}}=.*"
    line: "{{item.key}}={{item.value}}"
  loop: "{{ awx_custom_vars | dict2items }}"
```
This allows you to supply a default password (and more) by creating the following dictionary:

```
awx_custom_vars:
  admin_password: "password"
  http_proxy: "http://proxy:port"
  https_proxy: "http://proxy:port"
```
This way of you can change al l vars defined in the inventory file.
It overlaps with pull request #36. Might be possible to add it there for a future  version.
